### ISSUE TITLE
Support of memory quotas is incomplete

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-project-quickstarters#319]
Current situations:
quotas enabled on -dev and -test (not yet on -cd) for scope `- NotTerminating `

When the build reaches the `oc start-build stage`, it times out, because the build pod fails, because wie have a quota that applies to NotTerminating pods.

See [quota documentation on OpenShift](https://docs.okd.io/3.11/admin_guide/quota.html).

There is either missing:

```
spec:
  completionDeadlineSeconds: 1800
```

or a resource limit

```
spec
 resources:
    limits:
      memory: 100Mi
    requests:
      memory: 10Mi
```
